Repository craft-ai/craft-ai-client-python, pull requests merged in 2020-10, with the labels that each got.

#211 Chore remove is_optional
  CHANGELOG.md
  craft_ai/interpreter_v2.py
  tests/data/pandas_valid_data.py
Labels: chore

#206 Bulk generators
  CHANGELOG.md
  craft_ai/client.py
  craft_ai/interpreter.py
  craft_ai/pandas/utils.py
  poetry.lock
  pyproject.toml
  tests/test_create_generators_bulk.py
  tests/test_delete_generators_bulk.py
  tests/test_get_agent_decision_tree.py
  tests/test_get_agents_decision_trees_bulk.py
  tests/test_get_generator_decision_tree.py
  tests/test_get_generators_decision_trees_bulk.py
Labels: feature

#213 fix update_version to also commit pyproject.toml
  CHANGELOG.md
  pyproject.toml
  scripts/update_version.sh
Labels: bug

#212 Change error of bulk when an empty payload is given
  CHANGELOG.md
  craft_ai/client.py
  tests/test_create_agents_bulk.py
  tests/test_delete_agents_bulk.py
Labels: chore

#214 Fix bug on timezone and on missing vlalues on add operations bulk
  CHANGELOG.md
  craft_ai/pandas/client.py
  tests/data/pandas_valid_data.py
  tests/test_pandas_add_agents_operations_bulk.py
Labels: chore
